// GENERATED CODE -- DO NOT EDIT!

// package: aserto.directory.v2
// file: aserto/directory/v2/directory.proto

import * as aserto_directory_v2_directory_pb from "../../../aserto/directory/v2/directory_pb";
import * as grpc from "grpc";

interface IDirectoryService extends grpc.ServiceDefinition<grpc.UntypedServiceImplementation> {
  getObjectType: grpc.MethodDefinition<aserto_directory_v2_directory_pb.GetObjectTypeRequest, aserto_directory_v2_directory_pb.GetObjectTypeResponse>;
  setObjectType: grpc.MethodDefinition<aserto_directory_v2_directory_pb.SetObjectTypeRequest, aserto_directory_v2_directory_pb.SetObjectTypeResponse>;
  deleteObjectType: grpc.MethodDefinition<aserto_directory_v2_directory_pb.DeleteObjectTypeRequest, aserto_directory_v2_directory_pb.DeleteObjectTypeResponse>;
  listObjectTypes: grpc.MethodDefinition<aserto_directory_v2_directory_pb.ListObjectTypesRequest, aserto_directory_v2_directory_pb.ListObjectTypesResponse>;
  getObjType: grpc.MethodDefinition<aserto_directory_v2_directory_pb.GetObjTypeRequest, aserto_directory_v2_directory_pb.GetObjTypeResponse>;
  getRelationType: grpc.MethodDefinition<aserto_directory_v2_directory_pb.GetRelationTypeRequest, aserto_directory_v2_directory_pb.GetRelationTypeResponse>;
  setRelationType: grpc.MethodDefinition<aserto_directory_v2_directory_pb.SetRelationTypeRequest, aserto_directory_v2_directory_pb.SetRelationTypeResponse>;
  deleteRelationType: grpc.MethodDefinition<aserto_directory_v2_directory_pb.DeleteRelationTypeRequest, aserto_directory_v2_directory_pb.DeleteRelationTypeResponse>;
  listRelationTypes: grpc.MethodDefinition<aserto_directory_v2_directory_pb.ListRelationTypesRequest, aserto_directory_v2_directory_pb.ListRelationTypesResponse>;
  getRelType: grpc.MethodDefinition<aserto_directory_v2_directory_pb.GetRelTypeRequest, aserto_directory_v2_directory_pb.GetRelTypeResponse>;
  getPermission: grpc.MethodDefinition<aserto_directory_v2_directory_pb.GetPermissionRequest, aserto_directory_v2_directory_pb.GetPermissionResponse>;
  setPermission: grpc.MethodDefinition<aserto_directory_v2_directory_pb.SetPermissionRequest, aserto_directory_v2_directory_pb.SetPermissionResponse>;
  deletePermission: grpc.MethodDefinition<aserto_directory_v2_directory_pb.DeletePermissionRequest, aserto_directory_v2_directory_pb.DeletePermissionResponse>;
  listPermissions: grpc.MethodDefinition<aserto_directory_v2_directory_pb.ListPermissionsRequest, aserto_directory_v2_directory_pb.ListPermissionsResponse>;
  getPerm: grpc.MethodDefinition<aserto_directory_v2_directory_pb.GetPermRequest, aserto_directory_v2_directory_pb.GetPermResponse>;
  getRelationTypePermission: grpc.MethodDefinition<aserto_directory_v2_directory_pb.GetRelationTypePermissionRequest, aserto_directory_v2_directory_pb.GetRelationTypePermissionResponse>;
  setRelationTypePermission: grpc.MethodDefinition<aserto_directory_v2_directory_pb.SetRelationTypePermissionRequest, aserto_directory_v2_directory_pb.SetRelationTypePermissionResponse>;
  deleteRelationTypePermission: grpc.MethodDefinition<aserto_directory_v2_directory_pb.DeleteRelationTypePermissionRequest, aserto_directory_v2_directory_pb.DeleteRelationTypePermissionResponse>;
  listRelationTypePermissions: grpc.MethodDefinition<aserto_directory_v2_directory_pb.ListRelationTypePermissionsRequest, aserto_directory_v2_directory_pb.ListRelationTypePermissionsResponse>;
  getObject: grpc.MethodDefinition<aserto_directory_v2_directory_pb.GetObjectRequest, aserto_directory_v2_directory_pb.GetObjectResponse>;
  setObject: grpc.MethodDefinition<aserto_directory_v2_directory_pb.SetObjectRequest, aserto_directory_v2_directory_pb.SetObjectResponse>;
  deleteObject: grpc.MethodDefinition<aserto_directory_v2_directory_pb.DeleteObjectRequest, aserto_directory_v2_directory_pb.DeleteObjectResponse>;
  listObjects: grpc.MethodDefinition<aserto_directory_v2_directory_pb.ListObjectsRequest, aserto_directory_v2_directory_pb.ListObjectsResponse>;
  getObj: grpc.MethodDefinition<aserto_directory_v2_directory_pb.GetObjRequest, aserto_directory_v2_directory_pb.GetObjResponse>;
  getRelation: grpc.MethodDefinition<aserto_directory_v2_directory_pb.GetRelationRequest, aserto_directory_v2_directory_pb.GetRelationResponse>;
  setRelation: grpc.MethodDefinition<aserto_directory_v2_directory_pb.SetRelationRequest, aserto_directory_v2_directory_pb.SetRelationResponse>;
  deleteRelation: grpc.MethodDefinition<aserto_directory_v2_directory_pb.DeleteRelationRequest, aserto_directory_v2_directory_pb.DeleteRelationResponse>;
  listRelations: grpc.MethodDefinition<aserto_directory_v2_directory_pb.ListRelationsRequest, aserto_directory_v2_directory_pb.ListRelationsResponse>;
  getRel: grpc.MethodDefinition<aserto_directory_v2_directory_pb.GetRelRequest, aserto_directory_v2_directory_pb.GetRelResponse>;
  loader: grpc.MethodDefinition<aserto_directory_v2_directory_pb.LoaderRequest, aserto_directory_v2_directory_pb.LoaderResponse>;
  listObjectGraph: grpc.MethodDefinition<aserto_directory_v2_directory_pb.ListObjectGraphRequest, aserto_directory_v2_directory_pb.ListObjectGraphResponse>;
  getGraph: grpc.MethodDefinition<aserto_directory_v2_directory_pb.GetGraphRequest, aserto_directory_v2_directory_pb.GetGraphResponse>;
  check: grpc.MethodDefinition<aserto_directory_v2_directory_pb.CheckRequest, aserto_directory_v2_directory_pb.CheckResponse>;
  checkRelation: grpc.MethodDefinition<aserto_directory_v2_directory_pb.CheckRelationRequest, aserto_directory_v2_directory_pb.CheckRelationResponse>;
  checkPermission: grpc.MethodDefinition<aserto_directory_v2_directory_pb.CheckPermissionRequest, aserto_directory_v2_directory_pb.CheckPermissionResponse>;
  info: grpc.MethodDefinition<aserto_directory_v2_directory_pb.InfoRequest, aserto_directory_v2_directory_pb.InfoResponse>;
}

export const DirectoryService: IDirectoryService;

export interface IDirectoryServer extends grpc.UntypedServiceImplementation {
  getObjectType: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.GetObjectTypeRequest, aserto_directory_v2_directory_pb.GetObjectTypeResponse>;
  setObjectType: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.SetObjectTypeRequest, aserto_directory_v2_directory_pb.SetObjectTypeResponse>;
  deleteObjectType: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.DeleteObjectTypeRequest, aserto_directory_v2_directory_pb.DeleteObjectTypeResponse>;
  listObjectTypes: grpc.handleServerStreamingCall<aserto_directory_v2_directory_pb.ListObjectTypesRequest, aserto_directory_v2_directory_pb.ListObjectTypesResponse>;
  getObjType: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.GetObjTypeRequest, aserto_directory_v2_directory_pb.GetObjTypeResponse>;
  getRelationType: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.GetRelationTypeRequest, aserto_directory_v2_directory_pb.GetRelationTypeResponse>;
  setRelationType: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.SetRelationTypeRequest, aserto_directory_v2_directory_pb.SetRelationTypeResponse>;
  deleteRelationType: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.DeleteRelationTypeRequest, aserto_directory_v2_directory_pb.DeleteRelationTypeResponse>;
  listRelationTypes: grpc.handleServerStreamingCall<aserto_directory_v2_directory_pb.ListRelationTypesRequest, aserto_directory_v2_directory_pb.ListRelationTypesResponse>;
  getRelType: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.GetRelTypeRequest, aserto_directory_v2_directory_pb.GetRelTypeResponse>;
  getPermission: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.GetPermissionRequest, aserto_directory_v2_directory_pb.GetPermissionResponse>;
  setPermission: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.SetPermissionRequest, aserto_directory_v2_directory_pb.SetPermissionResponse>;
  deletePermission: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.DeletePermissionRequest, aserto_directory_v2_directory_pb.DeletePermissionResponse>;
  listPermissions: grpc.handleServerStreamingCall<aserto_directory_v2_directory_pb.ListPermissionsRequest, aserto_directory_v2_directory_pb.ListPermissionsResponse>;
  getPerm: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.GetPermRequest, aserto_directory_v2_directory_pb.GetPermResponse>;
  getRelationTypePermission: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.GetRelationTypePermissionRequest, aserto_directory_v2_directory_pb.GetRelationTypePermissionResponse>;
  setRelationTypePermission: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.SetRelationTypePermissionRequest, aserto_directory_v2_directory_pb.SetRelationTypePermissionResponse>;
  deleteRelationTypePermission: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.DeleteRelationTypePermissionRequest, aserto_directory_v2_directory_pb.DeleteRelationTypePermissionResponse>;
  listRelationTypePermissions: grpc.handleServerStreamingCall<aserto_directory_v2_directory_pb.ListRelationTypePermissionsRequest, aserto_directory_v2_directory_pb.ListRelationTypePermissionsResponse>;
  getObject: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.GetObjectRequest, aserto_directory_v2_directory_pb.GetObjectResponse>;
  setObject: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.SetObjectRequest, aserto_directory_v2_directory_pb.SetObjectResponse>;
  deleteObject: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.DeleteObjectRequest, aserto_directory_v2_directory_pb.DeleteObjectResponse>;
  listObjects: grpc.handleServerStreamingCall<aserto_directory_v2_directory_pb.ListObjectsRequest, aserto_directory_v2_directory_pb.ListObjectsResponse>;
  getObj: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.GetObjRequest, aserto_directory_v2_directory_pb.GetObjResponse>;
  getRelation: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.GetRelationRequest, aserto_directory_v2_directory_pb.GetRelationResponse>;
  setRelation: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.SetRelationRequest, aserto_directory_v2_directory_pb.SetRelationResponse>;
  deleteRelation: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.DeleteRelationRequest, aserto_directory_v2_directory_pb.DeleteRelationResponse>;
  listRelations: grpc.handleServerStreamingCall<aserto_directory_v2_directory_pb.ListRelationsRequest, aserto_directory_v2_directory_pb.ListRelationsResponse>;
  getRel: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.GetRelRequest, aserto_directory_v2_directory_pb.GetRelResponse>;
  loader: grpc.handleBidiStreamingCall<aserto_directory_v2_directory_pb.LoaderRequest, aserto_directory_v2_directory_pb.LoaderResponse>;
  listObjectGraph: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.ListObjectGraphRequest, aserto_directory_v2_directory_pb.ListObjectGraphResponse>;
  getGraph: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.GetGraphRequest, aserto_directory_v2_directory_pb.GetGraphResponse>;
  check: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.CheckRequest, aserto_directory_v2_directory_pb.CheckResponse>;
  checkRelation: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.CheckRelationRequest, aserto_directory_v2_directory_pb.CheckRelationResponse>;
  checkPermission: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.CheckPermissionRequest, aserto_directory_v2_directory_pb.CheckPermissionResponse>;
  info: grpc.handleUnaryCall<aserto_directory_v2_directory_pb.InfoRequest, aserto_directory_v2_directory_pb.InfoResponse>;
}

export class DirectoryClient extends grpc.Client {
  constructor(address: string, credentials: grpc.ChannelCredentials, options?: object);
  getObjectType(argument: aserto_directory_v2_directory_pb.GetObjectTypeRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetObjectTypeResponse>): grpc.ClientUnaryCall;
  getObjectType(argument: aserto_directory_v2_directory_pb.GetObjectTypeRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetObjectTypeResponse>): grpc.ClientUnaryCall;
  getObjectType(argument: aserto_directory_v2_directory_pb.GetObjectTypeRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetObjectTypeResponse>): grpc.ClientUnaryCall;
  setObjectType(argument: aserto_directory_v2_directory_pb.SetObjectTypeRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetObjectTypeResponse>): grpc.ClientUnaryCall;
  setObjectType(argument: aserto_directory_v2_directory_pb.SetObjectTypeRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetObjectTypeResponse>): grpc.ClientUnaryCall;
  setObjectType(argument: aserto_directory_v2_directory_pb.SetObjectTypeRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetObjectTypeResponse>): grpc.ClientUnaryCall;
  deleteObjectType(argument: aserto_directory_v2_directory_pb.DeleteObjectTypeRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeleteObjectTypeResponse>): grpc.ClientUnaryCall;
  deleteObjectType(argument: aserto_directory_v2_directory_pb.DeleteObjectTypeRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeleteObjectTypeResponse>): grpc.ClientUnaryCall;
  deleteObjectType(argument: aserto_directory_v2_directory_pb.DeleteObjectTypeRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeleteObjectTypeResponse>): grpc.ClientUnaryCall;
  listObjectTypes(argument: aserto_directory_v2_directory_pb.ListObjectTypesRequest, metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientReadableStream<aserto_directory_v2_directory_pb.ListObjectTypesResponse>;
  listObjectTypes(argument: aserto_directory_v2_directory_pb.ListObjectTypesRequest, metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientReadableStream<aserto_directory_v2_directory_pb.ListObjectTypesResponse>;
  getObjType(argument: aserto_directory_v2_directory_pb.GetObjTypeRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetObjTypeResponse>): grpc.ClientUnaryCall;
  getObjType(argument: aserto_directory_v2_directory_pb.GetObjTypeRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetObjTypeResponse>): grpc.ClientUnaryCall;
  getObjType(argument: aserto_directory_v2_directory_pb.GetObjTypeRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetObjTypeResponse>): grpc.ClientUnaryCall;
  getRelationType(argument: aserto_directory_v2_directory_pb.GetRelationTypeRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetRelationTypeResponse>): grpc.ClientUnaryCall;
  getRelationType(argument: aserto_directory_v2_directory_pb.GetRelationTypeRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetRelationTypeResponse>): grpc.ClientUnaryCall;
  getRelationType(argument: aserto_directory_v2_directory_pb.GetRelationTypeRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetRelationTypeResponse>): grpc.ClientUnaryCall;
  setRelationType(argument: aserto_directory_v2_directory_pb.SetRelationTypeRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetRelationTypeResponse>): grpc.ClientUnaryCall;
  setRelationType(argument: aserto_directory_v2_directory_pb.SetRelationTypeRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetRelationTypeResponse>): grpc.ClientUnaryCall;
  setRelationType(argument: aserto_directory_v2_directory_pb.SetRelationTypeRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetRelationTypeResponse>): grpc.ClientUnaryCall;
  deleteRelationType(argument: aserto_directory_v2_directory_pb.DeleteRelationTypeRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeleteRelationTypeResponse>): grpc.ClientUnaryCall;
  deleteRelationType(argument: aserto_directory_v2_directory_pb.DeleteRelationTypeRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeleteRelationTypeResponse>): grpc.ClientUnaryCall;
  deleteRelationType(argument: aserto_directory_v2_directory_pb.DeleteRelationTypeRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeleteRelationTypeResponse>): grpc.ClientUnaryCall;
  listRelationTypes(argument: aserto_directory_v2_directory_pb.ListRelationTypesRequest, metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientReadableStream<aserto_directory_v2_directory_pb.ListRelationTypesResponse>;
  listRelationTypes(argument: aserto_directory_v2_directory_pb.ListRelationTypesRequest, metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientReadableStream<aserto_directory_v2_directory_pb.ListRelationTypesResponse>;
  getRelType(argument: aserto_directory_v2_directory_pb.GetRelTypeRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetRelTypeResponse>): grpc.ClientUnaryCall;
  getRelType(argument: aserto_directory_v2_directory_pb.GetRelTypeRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetRelTypeResponse>): grpc.ClientUnaryCall;
  getRelType(argument: aserto_directory_v2_directory_pb.GetRelTypeRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetRelTypeResponse>): grpc.ClientUnaryCall;
  getPermission(argument: aserto_directory_v2_directory_pb.GetPermissionRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetPermissionResponse>): grpc.ClientUnaryCall;
  getPermission(argument: aserto_directory_v2_directory_pb.GetPermissionRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetPermissionResponse>): grpc.ClientUnaryCall;
  getPermission(argument: aserto_directory_v2_directory_pb.GetPermissionRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetPermissionResponse>): grpc.ClientUnaryCall;
  setPermission(argument: aserto_directory_v2_directory_pb.SetPermissionRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetPermissionResponse>): grpc.ClientUnaryCall;
  setPermission(argument: aserto_directory_v2_directory_pb.SetPermissionRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetPermissionResponse>): grpc.ClientUnaryCall;
  setPermission(argument: aserto_directory_v2_directory_pb.SetPermissionRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetPermissionResponse>): grpc.ClientUnaryCall;
  deletePermission(argument: aserto_directory_v2_directory_pb.DeletePermissionRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeletePermissionResponse>): grpc.ClientUnaryCall;
  deletePermission(argument: aserto_directory_v2_directory_pb.DeletePermissionRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeletePermissionResponse>): grpc.ClientUnaryCall;
  deletePermission(argument: aserto_directory_v2_directory_pb.DeletePermissionRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeletePermissionResponse>): grpc.ClientUnaryCall;
  listPermissions(argument: aserto_directory_v2_directory_pb.ListPermissionsRequest, metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientReadableStream<aserto_directory_v2_directory_pb.ListPermissionsResponse>;
  listPermissions(argument: aserto_directory_v2_directory_pb.ListPermissionsRequest, metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientReadableStream<aserto_directory_v2_directory_pb.ListPermissionsResponse>;
  getPerm(argument: aserto_directory_v2_directory_pb.GetPermRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetPermResponse>): grpc.ClientUnaryCall;
  getPerm(argument: aserto_directory_v2_directory_pb.GetPermRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetPermResponse>): grpc.ClientUnaryCall;
  getPerm(argument: aserto_directory_v2_directory_pb.GetPermRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetPermResponse>): grpc.ClientUnaryCall;
  getRelationTypePermission(argument: aserto_directory_v2_directory_pb.GetRelationTypePermissionRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetRelationTypePermissionResponse>): grpc.ClientUnaryCall;
  getRelationTypePermission(argument: aserto_directory_v2_directory_pb.GetRelationTypePermissionRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetRelationTypePermissionResponse>): grpc.ClientUnaryCall;
  getRelationTypePermission(argument: aserto_directory_v2_directory_pb.GetRelationTypePermissionRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetRelationTypePermissionResponse>): grpc.ClientUnaryCall;
  setRelationTypePermission(argument: aserto_directory_v2_directory_pb.SetRelationTypePermissionRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetRelationTypePermissionResponse>): grpc.ClientUnaryCall;
  setRelationTypePermission(argument: aserto_directory_v2_directory_pb.SetRelationTypePermissionRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetRelationTypePermissionResponse>): grpc.ClientUnaryCall;
  setRelationTypePermission(argument: aserto_directory_v2_directory_pb.SetRelationTypePermissionRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetRelationTypePermissionResponse>): grpc.ClientUnaryCall;
  deleteRelationTypePermission(argument: aserto_directory_v2_directory_pb.DeleteRelationTypePermissionRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeleteRelationTypePermissionResponse>): grpc.ClientUnaryCall;
  deleteRelationTypePermission(argument: aserto_directory_v2_directory_pb.DeleteRelationTypePermissionRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeleteRelationTypePermissionResponse>): grpc.ClientUnaryCall;
  deleteRelationTypePermission(argument: aserto_directory_v2_directory_pb.DeleteRelationTypePermissionRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeleteRelationTypePermissionResponse>): grpc.ClientUnaryCall;
  listRelationTypePermissions(argument: aserto_directory_v2_directory_pb.ListRelationTypePermissionsRequest, metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientReadableStream<aserto_directory_v2_directory_pb.ListRelationTypePermissionsResponse>;
  listRelationTypePermissions(argument: aserto_directory_v2_directory_pb.ListRelationTypePermissionsRequest, metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientReadableStream<aserto_directory_v2_directory_pb.ListRelationTypePermissionsResponse>;
  getObject(argument: aserto_directory_v2_directory_pb.GetObjectRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetObjectResponse>): grpc.ClientUnaryCall;
  getObject(argument: aserto_directory_v2_directory_pb.GetObjectRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetObjectResponse>): grpc.ClientUnaryCall;
  getObject(argument: aserto_directory_v2_directory_pb.GetObjectRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetObjectResponse>): grpc.ClientUnaryCall;
  setObject(argument: aserto_directory_v2_directory_pb.SetObjectRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetObjectResponse>): grpc.ClientUnaryCall;
  setObject(argument: aserto_directory_v2_directory_pb.SetObjectRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetObjectResponse>): grpc.ClientUnaryCall;
  setObject(argument: aserto_directory_v2_directory_pb.SetObjectRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetObjectResponse>): grpc.ClientUnaryCall;
  deleteObject(argument: aserto_directory_v2_directory_pb.DeleteObjectRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeleteObjectResponse>): grpc.ClientUnaryCall;
  deleteObject(argument: aserto_directory_v2_directory_pb.DeleteObjectRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeleteObjectResponse>): grpc.ClientUnaryCall;
  deleteObject(argument: aserto_directory_v2_directory_pb.DeleteObjectRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeleteObjectResponse>): grpc.ClientUnaryCall;
  listObjects(argument: aserto_directory_v2_directory_pb.ListObjectsRequest, metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientReadableStream<aserto_directory_v2_directory_pb.ListObjectsResponse>;
  listObjects(argument: aserto_directory_v2_directory_pb.ListObjectsRequest, metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientReadableStream<aserto_directory_v2_directory_pb.ListObjectsResponse>;
  getObj(argument: aserto_directory_v2_directory_pb.GetObjRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetObjResponse>): grpc.ClientUnaryCall;
  getObj(argument: aserto_directory_v2_directory_pb.GetObjRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetObjResponse>): grpc.ClientUnaryCall;
  getObj(argument: aserto_directory_v2_directory_pb.GetObjRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetObjResponse>): grpc.ClientUnaryCall;
  getRelation(argument: aserto_directory_v2_directory_pb.GetRelationRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetRelationResponse>): grpc.ClientUnaryCall;
  getRelation(argument: aserto_directory_v2_directory_pb.GetRelationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetRelationResponse>): grpc.ClientUnaryCall;
  getRelation(argument: aserto_directory_v2_directory_pb.GetRelationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetRelationResponse>): grpc.ClientUnaryCall;
  setRelation(argument: aserto_directory_v2_directory_pb.SetRelationRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetRelationResponse>): grpc.ClientUnaryCall;
  setRelation(argument: aserto_directory_v2_directory_pb.SetRelationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetRelationResponse>): grpc.ClientUnaryCall;
  setRelation(argument: aserto_directory_v2_directory_pb.SetRelationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.SetRelationResponse>): grpc.ClientUnaryCall;
  deleteRelation(argument: aserto_directory_v2_directory_pb.DeleteRelationRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeleteRelationResponse>): grpc.ClientUnaryCall;
  deleteRelation(argument: aserto_directory_v2_directory_pb.DeleteRelationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeleteRelationResponse>): grpc.ClientUnaryCall;
  deleteRelation(argument: aserto_directory_v2_directory_pb.DeleteRelationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.DeleteRelationResponse>): grpc.ClientUnaryCall;
  listRelations(argument: aserto_directory_v2_directory_pb.ListRelationsRequest, metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientReadableStream<aserto_directory_v2_directory_pb.ListRelationsResponse>;
  listRelations(argument: aserto_directory_v2_directory_pb.ListRelationsRequest, metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientReadableStream<aserto_directory_v2_directory_pb.ListRelationsResponse>;
  getRel(argument: aserto_directory_v2_directory_pb.GetRelRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetRelResponse>): grpc.ClientUnaryCall;
  getRel(argument: aserto_directory_v2_directory_pb.GetRelRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetRelResponse>): grpc.ClientUnaryCall;
  getRel(argument: aserto_directory_v2_directory_pb.GetRelRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetRelResponse>): grpc.ClientUnaryCall;
  loader(metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientDuplexStream<aserto_directory_v2_directory_pb.LoaderRequest, aserto_directory_v2_directory_pb.LoaderResponse>;
  loader(metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientDuplexStream<aserto_directory_v2_directory_pb.LoaderRequest, aserto_directory_v2_directory_pb.LoaderResponse>;
  listObjectGraph(argument: aserto_directory_v2_directory_pb.ListObjectGraphRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.ListObjectGraphResponse>): grpc.ClientUnaryCall;
  listObjectGraph(argument: aserto_directory_v2_directory_pb.ListObjectGraphRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.ListObjectGraphResponse>): grpc.ClientUnaryCall;
  listObjectGraph(argument: aserto_directory_v2_directory_pb.ListObjectGraphRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.ListObjectGraphResponse>): grpc.ClientUnaryCall;
  getGraph(argument: aserto_directory_v2_directory_pb.GetGraphRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetGraphResponse>): grpc.ClientUnaryCall;
  getGraph(argument: aserto_directory_v2_directory_pb.GetGraphRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetGraphResponse>): grpc.ClientUnaryCall;
  getGraph(argument: aserto_directory_v2_directory_pb.GetGraphRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.GetGraphResponse>): grpc.ClientUnaryCall;
  check(argument: aserto_directory_v2_directory_pb.CheckRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.CheckResponse>): grpc.ClientUnaryCall;
  check(argument: aserto_directory_v2_directory_pb.CheckRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.CheckResponse>): grpc.ClientUnaryCall;
  check(argument: aserto_directory_v2_directory_pb.CheckRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.CheckResponse>): grpc.ClientUnaryCall;
  checkRelation(argument: aserto_directory_v2_directory_pb.CheckRelationRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.CheckRelationResponse>): grpc.ClientUnaryCall;
  checkRelation(argument: aserto_directory_v2_directory_pb.CheckRelationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.CheckRelationResponse>): grpc.ClientUnaryCall;
  checkRelation(argument: aserto_directory_v2_directory_pb.CheckRelationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.CheckRelationResponse>): grpc.ClientUnaryCall;
  checkPermission(argument: aserto_directory_v2_directory_pb.CheckPermissionRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.CheckPermissionResponse>): grpc.ClientUnaryCall;
  checkPermission(argument: aserto_directory_v2_directory_pb.CheckPermissionRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.CheckPermissionResponse>): grpc.ClientUnaryCall;
  checkPermission(argument: aserto_directory_v2_directory_pb.CheckPermissionRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.CheckPermissionResponse>): grpc.ClientUnaryCall;
  info(argument: aserto_directory_v2_directory_pb.InfoRequest, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.InfoResponse>): grpc.ClientUnaryCall;
  info(argument: aserto_directory_v2_directory_pb.InfoRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.InfoResponse>): grpc.ClientUnaryCall;
  info(argument: aserto_directory_v2_directory_pb.InfoRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<aserto_directory_v2_directory_pb.InfoResponse>): grpc.ClientUnaryCall;
}
