name: ci

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      proto_ref:
      proto_sha:
  push:
    branches:
      - main
      - v*
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for PRs
  pull_request:
env:
  VAULT_ADDR: https://vault.eng.aserto.com/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Read Configuration
      uses: hashicorp/vault-action@v3
      id: vault
      with:
        url: ${{ env.VAULT_ADDR }}
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          kv/data/github  "SSH_PRIVATE_KEY"     | SSH_PRIVATE_KEY;
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Yarn Install
      run: yarn install

    - name: Generate
      run: yarn gen

    - name: Commit changes
      if: github.event_name == 'workflow_dispatch'
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Commit from GitHub Actions (ci)'
        add: 'src'
        push: origin HEAD:main

